name: sad_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.8.1
  cloud_firestore: ^5.5.1
  firebase_auth: ^5.3.4
  google_fonts: ^6.2.1
  provider: ^6.1.2

  #flutter_modular: ^6.3.4
  flutter_modular: ^5.0.3
  flutter_bloc: ^8.1.2
  flutter_svg: ^2.0.2
  flutter_facebook_auth: ^6.0.2
  google_sign_in: ^6.1.5
  firebase_storage: ^12.3.7
  firebase_dynamic_links: ^6.0.11
  permission_handler: ^11.0.1
  #contacts_service: ^0.6.3
  csv: ^6.0.0
  path_provider: ^2.0.5
  #share: ^2.0.4
  file_picker: ^8.1.4
  lottie: ^3.2.0
  logger: ^2.0.2+1
  url_launcher: ^6.0.20
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  easy_localization: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.1
  flutter_lints: ^5.0.0
  bloc_test: ^9.1.1
  flutter_native_splash: ^2.2.19
  flutter_launcher_icons: ^0.14.2
  build_runner: ^2.3.3
  json_serializable: ^6.6.1

targets:
  $default:
    builders:
      json_serializable:
        options:
          # Options configure how source code is generated for every
          # `@JsonSerializable`-annotated class in the package.
          #
          # The default value for each is listed.
          any_map: false
          checked: false
          constructor: ""
          create_factory: true
          create_field_map: false
          create_per_field_to_json: false
          create_to_json: true
          disallow_unrecognized_keys: false
          explicit_to_json: true
          field_rename: none
          generic_argument_factories: false
          ignore_unannotated: false
          include_if_null: true

flutter_native_splash:
  color: "#192024"
  image: assets/images/logo_transparent.png
  color_dark: "#192024"
  image_dark: assets/images/logo_transparent.png
  android: true
  ios: true
  web: false
  android_gravity: center
  ios_content_mode: center

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/images/logo_transparent.png"
  image_path_android: "assets/images/logo_transparent.png"

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/images_svg/
    - assets/animation_json/
    - assets/translations/