// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'email.freezed.dart';
// optional: Since our Email class is serializable, we must add this line.
// But if Email was not serializable, we could skip it.
part 'email.g.dart';

@freezed
class Email with _$Email {
  const factory Email({
    required String? label,
    required String? value,
  }) = _Email;

  factory Email.fromJson(Map<String, Object?> json) => _$EmailFromJson(json);
}
