// This file is "main.dart"
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';
import 'package:sad_app/app/modules/home/models/specialties/specialties_model.dart';
import 'package:sad_app/app/modules/home/models/teams/teams_model.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'professional_model.freezed.dart';
// optional: Since our ProfessionalModel class is serializable, we must add this line.
// But if ProfessionalModel was not serializable, we could skip it.
part 'professional_model.g.dart';

@freezed
class ProfessionalModel with _$ProfessionalModel {
  const factory ProfessionalModel({
    required String? id,
    required DateTime? createdAt,
    required String? email,
    required SpecialtiesModel? specialtyRef,
    required String? name,
    required TeamsModel? teamRef,
  }) = _ProfessionalModel;

  factory ProfessionalModel.fromJson(Map<String, Object?> json) =>
      _$ProfessionalModelFromJson(json);

  factory ProfessionalModel.fromFirestore(DocumentSnapshot doc) {
    Map data = doc.data() as Map;
    return ProfessionalModel(
      id: doc.id,
      name: data['name'] ?? '',
      email: data['email'] ?? '',
      specialtyRef: data['specialtyId'],
      teamRef: data['teamId'],
      createdAt: data['createdAt'] ?? '',
    );
  }
}
