// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'phone.freezed.dart';
// optional: Since our Phone class is serializable, we must add this line.
// But if Phone was not serializable, we could skip it.
part 'phone.g.dart';

@freezed
class Phone with _$Phone {
  const factory Phone({
    required String? label,
    required String? value,
  }) = _Phone;

  factory Phone.fromJson(Map<String, Object?> json) => _$PhoneFromJson(json);
}
