// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'donate_component.freezed.dart';
// optional: Since our ContactModel class is serializable, we must add this line.
// But if ContactModel was not serializable, we could skip it.
part 'donate_component.g.dart';

@freezed
class DonateComponent with _$DonateComponent {
  const factory DonateComponent({
    int? userId,
    required bool? showCheckedPix,
    required bool? showCheckedBitcoin,
    required bool? showCheckedEthereum,
    required bool? showCheckedTether,
  }) = _DonateComponent;

  factory DonateComponent.fromJson(Map<String, Object?> json) =>
      _$DonateComponentFromJson(json);

  factory DonateComponent.init() {
    return const DonateComponent(
      showCheckedPix: false,
      showCheckedBitcoin: false,
      showCheckedEthereum: false,
      showCheckedTether: false,
    );
  }
}
