// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'postal_address_model.freezed.dart';
// optional: Since our PostalAddressModel class is serializable, we must add this line.
// But if PostalAddressModel was not serializable, we could skip it.
part 'postal_address_model.g.dart';

@freezed
class PostalAddressModel with _$PostalAddressModel {
  const factory PostalAddressModel(
      {required String? label,
      required String? street,
      required String? city,
      required String? postcode,
      required String? region,
      required String? country}) = _PostalAddressModel;

  factory PostalAddressModel.fromJson(Map<String, Object?> json) =>
      _$PostalAddressModelFromJson(json);
}
