import 'package:firebase_auth/firebase_auth.dart';
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'auth_state_freezed.freezed.dart';
// optional: Since our User class is serializable, we must add this line.
part 'auth_state_freezed.g.dart';

@freezed
@JsonSerializable(explicitToJson: true)
class AuthState with _$AuthState {
  const factory AuthState({
    required bool? isLoading,
    required bool? successfullyReset,
    @JsonKey(
      name: 'user',
      fromJson: userFromJson,
      toJson: userToJson,
    )
    required User? user,
    required String? email,
    required String? error,
    required bool? isEmailVerified,
    required String? oobCode,
  }) = _AuthState;

  /* factory AuthState.fromJson(Map<String, Object?> json) =>
      _$AuthStateFromJson(json); */

  factory AuthState.init() => const AuthState(
        email: null,
        error: null,
        isLoading: false,
        successfullyReset: false,
        user: null,
        isEmailVerified: false,
        oobCode: null,
      );
}

User? userFromJson(User? user) {
  return user;
}

User? userToJson(User? user) => user;
