// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

import '../email/email.dart';
import '../phone/phone.dart';
import '../postal_addresses/postal_address_model.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'contact_model.freezed.dart';
// optional: Since our ContactModel class is serializable, we must add this line.
// But if ContactModel was not serializable, we could skip it.
part 'contact_model.g.dart';

@freezed
class ContactModel with _$ContactModel {
  const factory ContactModel({
    int? userId,
    required String? displayName,
    required String? givenName,
    required String? middleName,
    required String? prefix,
    required String? suffix,
    required String? familyName,
    required String? company,
    required String? jobTitle,
    required List<Email>? emails,
    required List<Phone>? phones,
    required List<PostalAddressModel>? postalAddresses,
  }) = _ContactModel;

  factory ContactModel.fromJson(Map<String, Object?> json) =>
      _$ContactModelFromJson(json);
}
