// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';
import 'package:sad_app/app/modules/home/models/teams/teams_model.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'patient_model.freezed.dart';
// optional: Since our PatientModel class is serializable, we must add this line.
// But if PatientModel was not serializable, we could skip it.
part 'patient_model.g.dart';

@freezed
class PatientModel with _$PatientModel {
  const factory PatientModel({
    required String? id,
    required String? email,
    required String? inactivationReason,
    required bool? isActive,
    required String? name,
    required TeamsModel? teamId,
  }) = _PatientModel;

  factory PatientModel.fromJson(Map<String, Object?> json) =>
      _$PatientModelFromJson(json);
}
