// This file is "main.dart"
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'specialties_model.freezed.dart';
// optional: Since our SpecialtiesModel class is serializable, we must add this line.
// But if SpecialtiesModel was not serializable, we could skip it.
part 'specialties_model.g.dart';

@freezed
class SpecialtiesModel with _$SpecialtiesModel {
  const factory SpecialtiesModel({
    required String? id,
    required String? name,
  }) = _SpecialtiesModel;

  factory SpecialtiesModel.fromJson(Map<String, Object?> json) =>
      _$SpecialtiesModelFromJson(json);

  factory SpecialtiesModel.fromFirestore(DocumentSnapshot doc) {
    Map data = doc.data() as Map;
    return SpecialtiesModel(
      id: doc.id,
      name: data['name'] ?? '',
    );
  }
}
